

def books():
    book = [
    {
        "id": 5,
        "title": "Clean Code - A Handbook of Agile Software Craftmanship ",
        "author": "Robert C.Martin ",
        "description": "Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Every year, countless hours and significant resources are lost because of poorly written code. But it doesn’t have to be that way. Noted software expert Robert C. Martin presents a revolutionary paradigm with Clean Code: A Handbook of Agile Software Craftsmanship . Martin has teamed up with his colleagues from Object Mentor to distill their best agile practice of cleaning code “on the fly” into a book that will instill within you the values of a software craftsman and make you a better programmer—but only if you work at it. What kind of work will you be doing? You’ll be reading code—lots of code. And you will be challenged to think about what’s right about that code, and what’s wrong with it. More importantly, you will be challenged to reassess your professional values and your commitment to your craft. Clean Code is divided into three parts. The first describes the principles, patterns, and practices of writing clean code. The second part consists of several case studies of increasing complexity. Each case study is an exercise in cleaning up code—of transforming a code base that has some problems into one that is sound and efficient. The third part is the payoff: a single chapter containing a list of heuristics and “smells” gathered while creating the case studies. The result is a knowledge base that describes the way we think when we write, read, and clean code. Readers will come away from this book understanding How to tell the difference between good and bad code How to write good code and how to transform bad code into good code How to create good \"name\"s, good functions, good objects, and good classes How to format code for maximum readability How to implement complete error handling without obscuring code logic How to unit test and practice test-driven development This book is a must for any developer, software engineer, project manager, team lead, or systems analyst with an interest in producing better code.",
        "price": 1000000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 6,
        "title": "The Clean Coder - A Code of Conduct for Professional Programmers",
        "author": "Robert C.Martin ",
        "description": "Programmers who endure and succeed amidst swirling uncertainty and nonstop pressure share a common attribute: They care deeply about the practice of creating software. They treat it as a craft. They are professionals. In The Clean Coder: A Code of Conduct for Professional Programmers, legendary software expert Robert C. Martin introduces the disciplines, techniques, tools, and practices of true software craftsmanship. This book is packed with practical advice-about everything from estimating and coding to refactoring and testing. It covers much more than technique: It is about attitude. Martin shows how to approach software development with honor, self-respect, and pride; work well and work clean; communicate and estimate faithfully; face difficult decisions with clarity and honesty; and understand that deep knowledge comes with a responsibility to act. Readers will learn What it means to behave as a true software craftsman How to deal with conflict, tight schedules, and unreasonable managers How to get into the flow of coding, and get past writers block How to handle unrelenting pressure and avoid burnout How to combine enduring attitudes with new development paradigms How to manage your time, and avoid blind alleys, marshes, bogs, and swamps How to foster environments where programmers and teams can thrive When to say No-and how to say it When to say Yes-and what yes really means Great software is something to marvel at: powerful, elegant, functional, a pleasure to work with as both a developer and as a user. Great software isnt written by machines. It is written by professionals with an unshakable commitment to craftsmanship. The Clean Coder will help you become one of them-and earn the pride and fulfillment that they alone possess.",
        "price": 1000000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 7,
        "title": "C++ For Beginners ",
        "author": "Erik Myers ",
        "description": "Would you like to program with C ++ easily and quickly? However, programming is not easy to make sure its really on the market. Designing is an incredibly valuable task for the developers and members of each business. With this book, you can decode and encode programming languages. If you want to program, you can take your entrepreneurship to the next level. Everyone has the same potential, and it can easily happen that the laughter evolves. In some of the chapters of this book, we will show you several top websites that will help you to improve.",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 8,
        "title": "Javascript&JQuery interactive front-end web development ",
        "author": "John Duckett ",
        "description": "In JavaScript & jQuery renowned \"author\" Jon Duckett discards the traditional programming book template and approaches writing code in a more relevant, less intimidating way.Full-color and packed with instructional graphics and photos, his books have gained a loyal following by illustrating programming in a way both instructive for newcomers and invaluable for seasoned coders.By discussing JavaScript and jQuery in a single text, Duckett ensures you will quickly be writing your own working scripts.Yet the book doesn't assume you have experience in either JavaScript or jQuery.By making use of popular jQuery plugins, Duckett illustrates techniques that would require pages upon pages of detailed explanation if you were being taught to create the plugins yourself.This durable and attractive hardcover edition is a book you will have open on your desk as a reference for years to come.",
        "price": 900000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 9,
        "title": "HARRY POTTER and PHILOSOPHER'S STONE ",
        "author": "J.K.Rowling ",
        "description": "Harry Potter is an ordinary boy who lives in a cupboard under the stairs at his Aunt Petunia and Uncle Vernon's house, which he thinks is normal for someone like him who's parents have been killed in a 'car crash'. He is bullied by them and his fat, spoilt cousin Dudley, and lives a very unremarkable life with only the odd hiccup (like his hair growing back overnight!) to cause him much to think about. That is until an owl turns up with a letter addressed to Harry and all hell breaks loose! He is literally rescued by a world where nothing is as it seems and magic lessons are the order of the day. Read and find out how Harry discovers his true heritage at Hogwarts School of Wizardry and Witchcraft, the reason behind his parents mysterious death, who is out to kill him, and how he uncovers the most amazing secret of all time, the fabled Philosopher's Stone!",
        "price": 270000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 27,
        "title": "Lối Sống Tối Giản Của Người Nhật ",
        "author": "Sasaki Fumio ",
        "description": "Lối sống tối giản là cách sống cắt giảm vật dụng xuống còn mức tối thiểu. Và cùng với cuộc sống ít đồ đạc, ta có thể để tâm nhiều hơn tới hạnh phúc, đó chính là chủ đề của cuốn sách này.",
        "price": 110000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 10,
        "title": "HARRY POTTER and CHAMBER of SECRET ",
        "author": "J.K.Rowling ",
        "description": "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone ...Dobby's sinister predictions seem to be coming true. These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON...",
        "price": 240000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 11,
        "title": "TÂM LÝ HỌC VỀ TIỀN ",
        "author": "Morgan Housel - Hoàng Thị Minh dịch ",
        "description": "Tiền bạc có ở khắp mọi nơi, nó ảnh hưởng đến tất cả chúng ta, và khiến phần lớn chúng ta bối rối. Mọi người nghĩ về nó theo những cách hơi khác nhau một chút. Nó mang lại những bài học có thể được áp dụng tới rất nhiều lĩnh vực trong cuộc sống, như rủi ro, sự tự tin, và hạnh phúc. Rất ít chủ đề cung cấp một lăng kính phóng to đầy quyền lực giúp giải thích vì sao mọi người lại hành xử theo cách họ làm hơn là về tiền bạc. Đó mới là một trong những chương trình hoành tráng nhất trên thế giới.",
        "price": 162500,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 12,
        "title": "nghệ thuật tập trung ",
        "author": "DaiGo - Thu Hằng dịch ",
        "description": "“Nghệ thuật tập trung: nâng cao năng suất, tối ưu thời gian, hiệu quả bất ngờ” dạy bạn cách tập trung vào một hành động và dần biến nó thành thói quen vững chắc. Sau đó, bạn sẽ có được sự tập trung tối thượng, năng suất làm việc cũng cao hơn nhiều người bình thường. Năng lực tập trung bạn sẽ trở thành vũ khí cả đời cho phép bạn kiểm soát toàn bộ cuộc sống của mình như mong muốn.",
        "price": 71400,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 13,
        "title": "Percy Jackson and The Olympians ",
        "author": "Rick Riordan ",
        "description": "Percy Jackson is a good kid, but he can’t seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse—Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy’s mom finds out, she knows it’s time that he knew the truth about where he came from, and that he go to the one place he’ll be safe. She sends Percy to Camp Half-Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena—Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.",
        "price": 160000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 14,
        "title": "HARRY POTTER and the PRISONER of AZKABAN ",
        "author": "J.K.Rowling ",
        "description": "An extraordinary creative achievement by an extraordinary talent, Jim Kay’s inspired reimagining of J.K. Rowling’s classic series has captured a devoted following worldwide. This stunning new fully illustrated edition of Harry Potter and the Prisoner of Azkaban brings more breathtaking scenes and unforgettable characters – including Sirius Black, Remus Lupin and Professor Trelawney. With paint, pencil and pixels, Kay conjures the wizarding world as we have never seen it before. Fizzing with magic and brimming with humour, this full-colour edition will captivate fans and new readers alike as Harry, now in his third year at Hogwarts School of Witchcraft and Wizardry, faces Dementors, death omens and – of course – danger.",
        "price": 250000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 15,
        "title": "HARRY POTTER and the GOBLET of FIRE ",
        "author": "J.K.Rowling ",
        "description": "The Triwizard Tour\"name\"nt is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his \"name\" is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive! These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers.",
        "price": 260000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 16,
        "title": "HARRY POTTER and the ORDER of the PHOENIX ",
        "author": "J.K.Rowling ",
        "description": "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone ...Dobby's sinister predictions seem to be coming true. These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON...",
        "price": 200000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 17,
        "title": "HARRY POTTER and the HALF-BLOOD PRINCE ",
        "author": "J.K.Rowling ",
        "description": "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny. These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON.",
        "price": 210000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 18,
        "title": "HARRY POTTER and the DEATHLY HALLOWS ",
        "author": "J.K.Rowling ",
        "description": "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is now broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry \"love\"s, and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy. These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON ...",
        "price": 220000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 19,
        "title": "Tuổi trẻ đáng giá bao nhiêu? ",
        "author": "Rosie Nguyễn ",
        "description": "\"Bạn hối tiếc vì không nắm bắt lấy một cơ hội nào đó, chẳng có ai phải mất ngủ. Bạn trải qua những ngày tháng nhạt nhẽo với công việc bạn căm ghét, người ta chẳng hề bận lòng. Bạn có chết mòn nơi xó tường với những ước mơ dang dở, đó không phải là việc của họ. Suy cho cùng, quyết định là ở bạn. Muốn có điều gì hay không là tùy bạn. hãy làm những điều bạn thích. Hãy đi theo tiếng nói trái tim. Hãy sống theo cách bạn cho là mình nên sống. Vì sau tất cả, chẳng ai quan tâm.\"",
        "price": 800000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 20,
        "title": "Đàn Ông Sao Hỏa - Đàn Bà Sao Kim ",
        "author": "John Gray ",
        "description": "Ngày xửa ngày xưa, những người sao Hỏa và sao Kim đã gặp gỡ, yêu nhau và sống hạnh phúc bởi họ tôn trọng và chấp nhận mọi điều khác biệt. Rồi họ đến Trái Đất và chứng lãng quên đã xảy ra: Họ quên rằng họ đến từ những hành tinh khác Hiểu biết về giới tính giúp chúng ta thêm khoan dung và biết tha thứ khi ai đó không đáp lại theo cách mà ta mong đợi. Tình chỉ đẹp khi còn dang dở, Cưới nhau về nham nhở lắm em ơi.Bởi kết hôn không phải là kết thúc một cuộc tình, mà nó mới là mở đầu cho rất nhiều những giai đoạn khó khăn mà cặp vợ chồng nào cũng phải trải qua. Bạn phải biết cách thích ứng và đối phó với nó để không rơi vào tình cảnh hôn nhân đổ vỡ.",
        "price": 160000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 21,
        "title": "Ổn Định Hay Tự Do ",
        "author": "Trương Học Vĩ ",
        "description": "ỔN ĐỊNH HAY TỰ DO (Yên ổn bạn thích không cho bạn được cuộc đời như mong muốn) - cuốn sách Best-seller dành cho thế hệ GEN Z, tiếp nối Hãy khiến tương lai biết ơn vì hiện tại bạn đã cố gắng hết mình.",
        "price": 81000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 22,
        "title": "Nghệ Thuật Tinh Tế Của Việc \"Đếch\" Quan Tâm ",
        "author": "Mark Manson ",
        "description": "Trong cuộc đời mình, tôi đã từng quan tâm về quá nhiều thứ. Đồng thời tôi cũng \"đếch\" quan tâm tới nhiều người, nhiều điều khác nữa. Và giống như con đường chưa từng được khai phá, chính những điều tôi chẳng thèm quan tâm ấy lại tạo nên sự khác biệt. Chìa khóa của một cuộc sống tốt đẹp không phải là quan tâm nhiều hơn, mà là quan tâm ít đi, chỉ quan tâm tới điều gì là thật, gần gũi và thực sự quan trọng.Cuốn này sẽ không dạy bạn cách để đạt tới điều này hay điều nọ, mà là làm thế nào để vứt bớt và buông bỏ... Nó sẽ hướng dẫn bạn cách nhắm mắt lại và tin rằng bạn có thể ngã ngửa ra đằng sau mà vẫn ổn. Nó sẽ dạy bạn: ĐỪNG CỐ” ",
        "price": 65000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 23,
        "title": "Sách Người Trong Muôn Nghề: Ngành IT có gì? ",
        "author": "Nhóm tác giả Spiderum ",
        "description": "Trong quá trình thực hiện bộ sách hướng nghiệp cho các bạn trẻ, chúng tôi cũng không ngừng trăn trở: Ngành CNTT có thật sự như vậy không? Làm sao để giúp các bạn trẻ có được một cái nhìn toàn diện và khách quan nhất về lĩnh vực rộng lớn này? Những cuốn sách về CNTT hiện có trên thị trường thường là tài liệu nặng tính kỹ thuật dành cho dân chuyên ngành, hoặc những bài viết ngắn với thông tin khá chung chung, hoặc chỉ có góc nhìn từ một cá nhân nên thiếu tính đa chiều. Vậy là nhóm độc giả nằm “lưng chừng” như những bạn học sinh cấp 3, sinh viên Đại học và các bậc phụ huynh đang quan tâm, muốn tìm hiểu về ngành CNTT bị bỏ mặc “bơ vơ”, biết đọc gì đây? Đó là lý do cuốn sách bạn đang cầm trên tay ra đời.",
        "price": 149000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 24,
        "title": "Sách Người trong muôn nghề ",
        "author": "Nhóm tác giả Spiderum ",
        "description": "Hầu hết những người trẻ đều đã từng hoặc đang trải qua cảm giác không biết mình thuộc về đâu. Khó khăn lớn nhất có lẽ không phải là kiếm được việc, mà là chọn được một nghề thực sự phù hợp với bản thân. Trên hành trình kiếm tìm ấy, người trẻ phải gánh trên vai rất nhiều áp lực vô hình từ gia đình và xã hội. Đi học thì ngành phải \"hot\", trường phải \"xịn\". Đi làm thì vị trí phải “oai\", lương tháng phải “cao\", công ty phải “khủng\". Chúng ta mải chạy theo những thứ bề nổi mà quên mất rằng mục đích sau cùng của việc chọn ngành, chọn nghề là giúp mình tìm được điểm giao thoa giữa năng lực, sở thích cá nhân với nhu cầu của xã hội.Người Trong Muôn Nghề hi vọng có thể kéo bạn lại gần hơn với mục đích bản chất ấy. Cuốn sách là tuyển tập những câu chuyện đi làm tâm huyết đến từ những cây viết dày dặn kinh nghiệm trong các lĩnh vực chuyên môn và những môi trường làm việc khác nhau. Những chia sẻ này sẽ giúp các bạn học sinh, sinh viên có một cái nhìn toàn diện hơn về thế giới công việc thực thụ",
        "price": 149000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 25,
        "title": "Sách Người trong muôn nghề: Ngành Kinh tế có gì? ",
        "author": "Nhóm tác giả Spiderum ",
        "description": "\"Người Trong Muôn Nghề: Ngành Kinh Tế Có Gì?\" tập hợp 21 bài viết chứa đựng những chia sẻ “thật và chất” của các tác giả - những người trực tiếp hoạt động trong đa dạng các vị trí liên quan đến khối Kinh tế. Họ ở đủ mọi độ tuổi, vị trí công việc, địa lý, giới tính: Từ những người vào nghề vài năm tới các đàn anh 30 năm trong nghề; Từ người học tập tại nước ngoài cho đến các bạn tốt nghiệp trong nước; Từ người làm giảng viên, nghiên cứu cho đến các doanh nhân lăn lộn thương trường; Từ chuyên gia đầu ngành cho đến những người có bộ óc “sừng sỏ” trong đầu tư, kinh doanh ở nước ngoài.",
        "price": 149000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 26,
        "title": "Cà Phê Cùng Tony ",
        "author": "Tony Buổi Sáng ",
        "description": "Có đôi khi vào những tháng năm bắt đầu vào đời, giữa vô vàn ngả rẽ và lời khuyên, khi rất nhiều dự định mà thiếu đôi phần định hướng, thì CẢM HỨNG là điều quan trọng để bạn trẻ bắt đầu bước chân đầu tiên trên con đường theo đuổi giấc mơ của mình. Cà Phê Cùng Tony là tập hợp những bài viết của tác giả Tony Buổi Sáng. Đúng như tên gọi, mỗi bài nhẹ nhàng như một tách cà phê, mà bạn trẻ có thể nhận ra một chút gì của chính mình hay bạn bè mình trong đó: Từ chuyện lớn như định vị bản thân giữa bạn bè quốc tế, cho đến chuyện nhỏ như nên chú ý những phép tắc xã giao thông thường.Chúng tôi tin rằng những người trẻ tuổi luôn mang trong mình khát khao vươn lên và tấm lòng hướng thiện, và có nhiều cách để động viên họ biến điều đó thành hành động. Nếu như tập sách nhỏ này có thể khơi gợi trong lòng bạn đọc trẻ một cảm hứng tốt đẹp, như tách cà phê thơm vào đầu ngày nắng mới, thì đó là niềm vui lớn của tác giả Tony Buổi Sáng.",
        "price": 64000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 28,
        "title": "Tôi Vẽ - Phương Pháp Tự Học Vẽ Truyện Tranh ",
        "author": "Nhóm tác giả ",
        "description": "“Tôi Vẽ\" với 300 trang sách bao gồm những kỹ năng cơ bản cần có của một họa sĩ truyện tranh, từ tạo hình nhân vật, thiết kế bối cảnh, biểu cảm, các kỹ thuật diễn họa cho đến luật phối cảnh. Đây là một cuốn cẩm nang tuyệt vời dành cho các bạn đang bắt đầu học vẽ truyện tranh. Những kiến thức này có thể không giúp các bạn vẽ đẹp ngay lập tức nhưng sẽ là nền tảng vững chắc giúp bạn hình thành các tiêu chuẩn chuyên nghiệp trong nghề và không mất thời gian tự mò mẫm. Phần minh họa cho các bài học cũng rất hấp dẫn và sáng tạo. Các tác giả đã sử dụng chính nhân vật và trang truyện của mình để làm rõ sự liên quan giữa lý thuyết và thực tế, tính ứng dụng rõ ràng của các kỹ thuật và quy trình sáng tác.",
        "price": 100000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 29,
        "title": "Tôi Thấy Hoa Vàng Trên Cỏ Xanh ",
        "author": "Nguyễn Nhật Ánh ",
        "description": "Ta bắt gặp trong Tôi Thấy Hoa Vàng Trên Cỏ Xanh một thế giới đấy bất ngờ và thi vị non trẻ với những suy ngẫm giản dị thôi nhưng gần gũi đến lạ. Câu chuyện của Tôi Thấy Hoa Vàng Trên Cỏ Xanh có chút này chút kia, để ai soi vào cũng thấy mình trong đó, kiểu như lá thư tình đầu đời của cu Thiều chẳng hạ ngây ngô và khờ khạo.",
        "price": 125000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 30,
        "title": "Cho Tôi Xin Một Vé Đi Tuổi Thơ ",
        "author": "Nguyễn Nhật Ánh ",
        "description": "Truyện Cho tôi xin một vé đi tuổi thơ là sáng tác mới nhất của nhà văn Nguyễn Nhật Ánh. Nhà văn mời người đọc lên chuyến tàu quay ngược trở lại thăm tuổi thơ và tình bạn dễ thương của 4 bạn nhỏ. Những trò chơi dễ thương thời bé, tính cách thật thà, thẳng thắn một cách thông minh và dại dột, những ước mơ tự do trong lòng… khiến cuốn sách có thể làm các bậc phụ huynh lo lắng rồi thở phào. Không chỉ thích hợp với người đọc trẻ, cuốn sách còn có thể hấp dẫn và thực sự có ích cho người lớn trong quan hệ với con mình.",
        "price": 63000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 31,
        "title": "Cô Gái Đến Từ Hôm Qua ",
        "author": "Nguyễn Nhật Ánh ",
        "description": "Nếu ngày xưa còn bé, Thư luôn tự hào mình là cậu con trai thông minh có quyền bắt nạt và sai khiến các cô bé cùng lứa tuổi thì giờ đây khi lớn lên, anh luôn khổ sở khi thấy mình ngu ngơ và bị con gái “xỏ mũi”. Và điều nghịch lý ấy xem ra càng “trớ trêu’ hơn, khi như một định mệnh, Thư nhận ra Việt An, cô bạn học thông minh thường làm mình bối rối bấy lâu nay chính là Tiểu Li, con bé hàng xóm ngốc nghếch từng hứng chịu những trò nghịch ngợm của mình hồi xưa.",
        "price": 80000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 32,
        "title": "Mắt Biếc ",
        "author": "Nguyễn Nhật Ánh ",
        "description": "Mắt biếc là một tác phẩm được nhiều người bình chọn là hay nhất của nhà văn Nguyễn Nhật Ánh. Tác phẩm này cũng đã được dịch giả Kato Sakae dịch sang tiếng Nhật để giới thiệu với độc giả Nhật Bản. “Tôi gửi tình yêu cho mùa hè, nhưng mùa hè không giữ nổi. Mùa hè chỉ biết ra hoa, phượng đỏ sân trường và tiếng ve nỉ non trong lá. Mùa hè ngây ngô, giống như tôi vậy. Nó chẳng làm được những điều tôi ký thác. Nó để Hà Lan đốt tôi, đốt rụi. Trái tim tôi cháy thành tro, rơi vãi trên đường về.”… Bởi sự trong sáng của một tình cảm, bởi cái kết thúc buồn, rất buồn khi xuyên suốt câu chuyện vẫn là những điều vui, buồn lẫn lộn …  ",
        "price": 100000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 33,
        "title": "Tôi Là Bêtô ",
        "author": "Nguyễn Nhật Ánh ",
        "description": "Tôi Là Bêtô là tác phẩm mới nhất của nhà văn chuyên viết cho thanh thiếu niên của Nguyễn Nhật Ánh. Anh đã được đông đảo bạn đọc biết đến qua các tác phẩm quen thuộc như Thằng quỷ nhỏ, Trại hoa vàng, Bong bóng lên trời, Cô gái đến từ hôm qua… và hai bộ truyện nhiều tập Kính vạn hoa và Chuyện xứ Lang Biang. Với Tôi là Bêtô, đây là lần đầu tiên anh viết một tác phẩm qua lời kể của một chú cún. Trong thiên truyện này, thế giới được nhìn một cách trong trẻo nhưng lồng trong đó không thiếu những ý tứ thâm trầm, khiến người đọc phải ngẫm nghĩ. Đây chắc chắn là tác phẩm không chỉ dành cho trẻ em.",
        "price": 67000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 34,
        "title": "Dữ Liệu Lớn - Big Data ",
        "author": "Bernard Marr ",
        "description": "Hiện nay, thế giới đang trở nên thông minh hơn. Chúng ta đang theo dõi và lưu trữ dữ liệu về mọi thứ, nên chúng ta có khả năng tiếp cận với nhiều khối dữ liệu lớn. Tuy nhiên, có rất nhiều vấn đề xoay quanh các khối dữ liệu lớn này. Tất cả chúng ta đều cần phải biết nó là gì và hoạt động như thế nào. Nhưng sự hiểu biết cơ bản về lý thuyết liệu có đủ cho bạn để tổ chức một cuộc họp chiến lược không? Điều khiến bạn trở nên khác với phần còn lại là biết cách sử dụng dữ liệu lớn để cải thiện hiệu suất và có được kết quả kinh doanh vững chắc. Cuốn sách Big Data – Dữ liệu lớn sẽ cung cấp cho bạn một sự hiểu biết rõ ràng, kế hoạch chi tiết và từng bước tiếp cận thông qua mô hình SMART: Khởi dầu với chiến lược, Đo lường các chỉ số và dữ liệu, Áp dụng các phương pháp phân tích, Báo cáo kết quả, Biến đổi doanh nghiệp.",
        "price": 110000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 35,
        "title": "Nguyên Tắc Thiết Kế Slide Chuẩn Ted ",
        "author": "Akash Karia ",
        "description": "Nguyên tắc thiết kế slide chuẩn TED không phải là sách vỡ lòng đầy đủ về việc thiết kế bài thuyết trình. Tuy nhiên, nó bao quát tất thảy các yếu tố cần thiết. Nguyên tắc thiết kế slide chuẩn TED được viết rất cô đọng phù hợp cho những người không muốn lãng phí thời gian vào những điều vô bổ. Trong cuốn sách này, bạn sẽ tìm thấy các ví dụ về những slide hấp dẫn từ các bài TED talk ấn tượng, cùng với đó là những nguyên tắc thiết thực mà bạn có thể vận dụng để khiến bài thuyết trình của mình trở nên sống động.",
        "price": 52000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 57,
        "title": "Late Beethoven: Music, Thought, Imagination ",
        "author": "Maynard Solomon ",
        "description": "In a series of powerful strokes, the music of Beethoven’s last years redefined his legacy and enlarged the realm of experience accessible to the creative imagination. Maynard Solomon’s Late Beethoven investigates the phenomenon of the final phase, focusing especially on the striking metamorphosis in Beethoven’s system of beliefs that began early in his fifth decade and eventually amounted to a sweeping realignment of his views of nature, antiquity, divinity, and human purpose.",
        "price": 510000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 36,
        "title": "Sword Art Online - Tập 2 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Tập 2 xoay quanh nhân vật chính Kirito và các cuộc gặp gỡ nhiều dấu ấn của cậu. Tuy cương quyết làm game thủ solo trong trò chơi tử thần Sword Art Online, nhưng bằng tính cách thu hút và tài năng đặc biệt của mình, Kirito vẫn gặp được những con người thú vị hoặc tuyệt vời suốt hành trình phá đảo. Trong SAO, ngoài Kirito và nhóm tấn công ra, còn có rất nhiều người chơi khác nữa. Họ tham gia hoạt động ở các ngành nghề đa dạng, và hỗ trợ đội ngũ chiến binh nơi tiền tuyến bằng chuyên môn và sở trường của mình. Tuy không thể đăng xuất, bắt buộc phải tồn tại trong thế giới trò chơi tàn khốc này, nhưng họ vẫn sống một cách sôi nổi, hăng hái và chấp nhận thách thức, có rơi nước mắt nhưng cũng có nụ cười. Chẳng hạn như Silica giỏi thuần hóa thú, Lisbeth chuyên rèn binh khí, hay Sachi một thiếu nữ mà Kirito không thể nào quê",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 37,
        "title": "Sword Art Online - Tập 3 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "FAIRY DANCE Rời trò chơi sinh tử Sword Art Online trở về hiện thực, Kirito lập tức đi tìm những người bạn kề vai sát cánh với mình trong trò chơi ấy. Dĩ nhiên cũng ráo riết kiếm tìm dấu vết người vợ yêu quý Asuna. Nhưng hóa ra Asuna vẫn chưa thoát thân được khỏi trò chơi. Hoàn toàn không hiểu tình hình này là thế nào, Kirito không khỏi sinh lòng tuyệt vọng. Manh mối duy nhất của cậu là một file ảnh lạ lùng cho thấy Asuna đứng trong một chiếc lồng với hình dạng “tinh linh”. Dường như cô đang bị giam hãm Alfheim Online, một trò chơi VRMMO tính năng cao. Để giải cứu Asuna, Kirito lao vào thế giới ALO đông đảo tinh linh ấy. Và câu chuyện Fairy Dance bắt đầu…",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 38,
        "title": "Sword Art Online - Tập 4 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Kirito thoát khỏi Sword Art Online, nhưng Asuna thì chưa. Để cứu cô, Kirito đã đăng nhập vào một game VRMMO rất đáng ngờ là ALfheim Online (ALO). ALO là một game phi hành next-gen. Ở đây, yếu tố phép thuật, khả năng phản ứng và phán đoán của game thủ giữ vai trò quyết định thắng bại. Bên cạnh đó, việc cho phép người chơi trở thành tinh linh và làm chủ hệ thống bay lượn cùng những công nghệ vượt trội không hề thua kém SAO đã khiến ALO hấp dẫn một lượng lớn game thủ. Trở thành một tinh linh Spriggan, Kirito tiến thẳng đến nơi giam giữ linh hồn Asuna, cũng chính là mục tiêu sau cùng của toàn bộ game thủ: “Cây Thế Giới”! Dọc đường đi, vì trúng mưu kế của nhóm game thủ tộc Salamander, Kirito rơi vào tình huống thập tử nhất sinh, nhưng nhờ sự giúp đỡ của Leafa một thiếu nữ tộc Sylph và Yui tiểu tiên chỉ đường, cuối cùng cậu vẫn giữ gìn được tính mạng. Rốt cuộc, Kirito cũng đến được gốc Cây Thế Giới. Nhưng khi đó, “bí mật” về mối quan hệ giữa Kirito và Leafa cũng dần hé lộ",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 39,
        "title": "Sword Art Online - Tập 5 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Một năm đã trôi qua kể từ \"sự cố SAO\". Một ngày nọ, Kirito bất ngờ nhận được một yêu cầu kì lạ từ Kikuoka Seijiro thuộc \"Phòng Quản lí Thế giới ảo\". Trong thế giới của sắt thép và súng đạn VRMMO “Gun Gale Online (GGO)\" bỗng xảy ra sự kiện \"Tay Súng Tử Thần\". Game thủ bị kẻ bí ẩn cầm súng đen bắn trúng trong trò chơi cũng sẽ chết ở thế giới thực… Kirito không thể từ chối, đành đồng ý hỗ trợ điều tra. Dù khá nghi ngờ chuyện thế giới ảo có thể sinh ra tác động vật lí lên thế giới thực, cậu vẫn đăng nhập vào GGO. Trong lúc đang loay hoay giữa một nơi hoàn toàn xa lạ tìm kiếm manh mối liên quan đến Tay Súng Tử Thần, Kirito đã nhận được sự giúp đỡ của Sinon - một game thủ nữ sử dụng khẩu súng bắn tỉa \"Hecate II\".",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 40,
        "title": "Sword Art Online - Tập 6 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Để làm rõ chân tướng sự kiện Tay Súng Tử Thần trong Gun Gale Online, một VRMMO chuyên về súng, Kirito đã đăng nhập vào GGO. Sau khi chuyển từ ALO sang đây, Kirito ngẫu nhiên gặp rắc rối vì nhân vật của cậu trông bề ngoài rất giống con gái, lại xinh đẹp. Được một tay súng nữ chỉ dẫn, cậu vượt qua vòng loại Bullet of Bullets một cách thuận lợi. Trong thế giới mà súng ống là bá chủ ấy, cậu là chiến binh duy nhất sử dụng kiếm ánh sáng, lại liên tục giành thắng lợi trong BoB. Phong cách chiến đấu độc đáo của cậu trở thành tiêu điểm sự kiện, kéo theo sự nổi tiếng bất đắc dĩ.",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 41,
        "title": "Sword Art Online - Tập 7 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Trong ALfhelm Online, một VRMMO thế hệ mới cho phép người chơi nhập vai các tinh linh biết bay, bỗng dưng xảy ra một chuyện lạ lùng. Tại phía bắc phố chính tầng 24 của thành nổi Aincrad ở vùng đất mới này, bỗng dưng xuất hiện một nhân vật bí hiểm. Nhân vật đó có biệt danh Tuyệt Kiếm, tự sáng tạo ra một Kiếm kĩ Nguyên bản và đem nó làm giải thưởng thách đấu tay đôi với các người chơi khác. Cuối cùng đánh bại tất cả bọn họ, thậm chí đánh bại cả Hắc kiếm sĩ Kirito. Asuna cũng khiêu chiến với Tuyệt Kiếm, nhưng cũng thất bại, dù chỉ trong gang tấc. Điều đáng ngạc nhiên là, khi trận quyết đấu kết thúc, Tuyệt Kiếm lại mời Asuna party với mình.",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 42,
        "title": "Sword Art Online - Tập 8 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Early And Late Vụ án trong khu dân cư. Một game thủ bị giết ở vùng tầng trung của SAO. Hiện trường vụ án là “khu dân cư”, nơi HP không thể giảm được. Nếu đây là một vụ PK thì thủ phạm thực hiện bằng cách nào? Người theo đuổi vụ án kì quái này là Kirito và Asuna. Caliber. Nhiệm vụ đoạt lấy Thánh kiếm Excalibur, vũ khí truyền thuyết của ALO, cuối cùng cũng bắt đầu. Lần thứ nhất, Kirito đã phải bỏ cuộc bởi lũ quái hộ vệ quá mạnh, nhưng lần này, cậu sẽ tái đấu một cách nghiêm túc. Phía sau nhiệm vụ ấy là một sự kiện ẩn hoành tráng… Ngày đầu tiên. Ngày đầu tiên SAO chính thức vận hành. Ngay sau khi Kayaba Akihito biến nơi đây thành một trò chơi sinh tử, Kirito đã quyết định mình phải làm gì để sống sót qua trò chơi này. Đó là tận dụng kinh nghiệm thời còn là beta-tester để hoàn thành ngay một nhiệm vụ và giành lấy thanh kiếm mạnh hơn trang bị ban đầu…",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 43,
        "title": "Sword Art Online - Tập 9 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Kirigaya Kazuto được giới thiệu đến làm thêm ở một doanh nghiệp tư nhân. Công việc là test máy FullDive thế hệ thứ 4. Thao tác của cậu rất đơn giản, chỉ việc nằm yên một chỗ để dive liên tục ba ngày cuối tuần, nhưng phần kí ức của hai thế giới thực và ảo lại bị ngăn cách hoàn toàn. Bởi thế, khi gặp Asuna và Shino vào tuần sau đó để nhận lời convert sang GGO tham gia giải đấu BoB lần thứ năm, cậu không nhớ được gì về thế giới ảo vừa test để kể cho họ. Sau khi chia tay Shino, Kazuto tiễn Asuna về nhà. Chỉ còn vài bước tới nơi thì họ bị một kẻ lạ mặt tấn công. Kazuto che chắn để Asuna chạy đi tìm người cứu, nhưng một tiếng động kinh hoàng đằng sau đã khiến Asuna dừng bước...",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 44,
        "title": "Sword Art Online - Tập 10 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Ở Nhật Bản hiện giờ có một trường đại học kĩ thuật, trong trường đó có một khoa về công nghệ Điện-Điện tử, trong khoa đó có một phòng nghiên cứu tên là Shigemura. Trong phòng này có một số sinh viên kinh người. Bốn năm nữa, một người trong số đó sẽ dùng một trò chơi thực tế ảo để cầm tù ý thức của một vạn người, chưa chơi xong chưa được đi ra. Sau đó có tầm bốn nghìn người chết. Vào ngày phá đảo, có một người chưa kịp đi ra đã bị vợt vào trò chơi thực tế ảo của người thứ hai, nơi hàng trăm người khác bị đẩy vào một thí nghiệm vô nhân đạo về não bộ. Chuyện này xảy ra vào sáu năm nữa. May lần này không có ai chết...",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 45,
        "title": "Sword Art Online - Tập 11 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Đã hai năm kể từ khi Kirito bước vào một thế giới tưởng tượng bí ẩn khác và gặp cậu bé tên Eugeo. Tại Học viện Kiếm thuật Bậc thầy Bắc Centoria, hai người họ đã tiến bộ để trở thành ...",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 46,
        "title": "Sword Art Online - Tập 12 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Cuối cùng Eugeo cũng gặp lại Alice, người con gái mà cậu đã mải miết tìm kiếm từ thời thơ ấu. Tuy nhiên, ở Alice hiện giờ không còn chút gì giống Alice của làng Rulid ngày xưa nữa. Alice này là người tới bắt Kirito và Eugeo, hai kẻ đã vi phạm Danh mục cấm. Cô không còn chút kí ức nào về thời thơ ấu, hơn thế nữa, còn tự xưng mình là Hiệp sĩ Chỉnh hợp. Kirito và Eugeo bị giam giữ trong hầm ngục Central Cathedral, biểu tượng của Giáo hội Công lý. Nhưng nhờ vào sự tháo vát của Kirito, họ đã trốn thoát thành công. Cardinal, một cô gái bí ẩn nhận biết được Kirito là người từ “bên ngoài”, đã trợ giúp hai thiếu niên đang nhắm đến đỉnh tòa tháp với mục đích mang “Alice thực sự” trở về! Tuy nhiên, chặn đường họ là những chiến binh mạnh nhất sinh ra từ Nghi lễ Synthesis…",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 47,
        "title": "Sword Art Online - Tập 13 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "“Nở ra, hoa hồng!” Kirito và Eugeo cùng lên thẳng tầng cao nhất của tòa tháp trắng Central Cathedral, biểu tượng của Giáo hội Công lý, cũng là nơi ở của tư tế tối cao Administrator. Một lần nữa, họ đối mặt với Hiệp sĩ Chỉnh hợp Alice (Kim Mộc Tê). Thuật chi phối vũ trang toàn diện của Kirito và Alice cùng bùng nổ, đục vỡ tường ngoài tòa tháp, làm hai người văng ra khỏi Cathedral. Dù bị chia tách với Kirito, Eugeo vẫn tin tưởng rằng bạn mình sẽ xoay xở sống được. Và tiếp tục lên các tầng trên một mình. Kẻ địch xuất hiện trước mặt cậu là Hiệp sĩ Chỉnh hợp lớn tuổi nhất, hùng mạnh nhất: Bercouli Synthesis One. Đối diện người anh hùng trong câu chuyện cổ tích ngày thơ bé, Eugeo tuốt mạnh thanh kiếm Aobara. Trận chiến hạ màn bằng sự ra đời của một kiếm sĩ mới. Không còn Kirito ở bên, Eugeo khoác vào người bộ giáp của Hiệp sĩ Chỉnh hợp. Trong đôi mắt cậu, lóe lên ánh sáng lạnh băng...",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 48,
        "title": "Sword Art Online - Tập 14 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Tòa tháp trắng Central Cathedral tượng trưng cho Giáo hội Công lý. Nhờ sự giúp đỡ của Cardinal, nhà hiền triết bị cách li trong tàng thư các, Eugeo và Kirito bắt đầu hành trình lên tầng 100, tầng cao nhất của Cathedral, nơi ở của tư tế tối cao Administrator. Mục đích của Eugeo là lấy lại “nguyên bản” cho Alice, nay đã bị biến thành Hiệp sĩ Chỉnh hợp, còn mục đích của Kirito là để cứu rỗi Underworld khỏi sự diệt vong. Họ đã đến tầng 99. Xuất hiện trước mắt Kirito và Alice lại là Eugeo. Nhưng là một Eugeo mặc giáp Hiệp sĩ Chỉnh hợp và đôi mắt lóe lên lạnh giá. Eugeo phũ phàng vung kiếm, Kirito bất đắc dĩ phải đánh trả. Lẽ nào điềm báo về trận chiến và li biệt mà cậu cảm nhận được trong tiếng sấm xa xăm vào ngày đầu khởi hành khỏi làng đã thành sự thật? Tiếng gọi thiết tha của Kirito liệu có lay chuyển được một Eugeo đã bị phong ấn kí ức? Alicization, phần “Nhân giới”, kết thúc!",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 49,
        "title": "Sword Art Online - Tập 15 (Tái Bản) ",
        "author": "Reki Kawahara ",
        "description": "Cái giá phải trả của việc đánh bại tư tế tối cao Administrator, là cái chết của Eugeo, và trạng thái tinh thần suy sụp của Kirito. Đã nửa năm trôi qua từ trận chiến tàn khốc ấy. Alice đưa Kirito về lại làng Rulid. Bấy giờ cậu đã không còn ý chí gì nữa, vẻ mặt thì trống rỗng, người lại ngồi trên xe lăn. Trao trả nhiệm vụ bảo vệ Nhân giới cho Bercouli, Alice chọn lựa sống đời yên ả cùng Kirito. Nhưng giai đoạn phụ tải cuối, như nhà hiền triết Cardinal tiên đoán, đang từng bước áp sát… Bầu không khí tà ác từ Vương quốc Bóng tối bắt đầu tràn sang Nhân giới. Quân đoàn Bóng tối khủng khiếp cuối cùng cũng đã rục rịch hành động.",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 58,
        "title": "Mindset: The New Psychology of Success ",
        "author": "Carol S. Dweck ",
        "description": "After decades of research, world-renowned Stanford University psychologist Carol S. Dweck, Ph.D., discovered a simple but groundbreaking idea: the power of mindset. In this brilliant book, she shows how success in school, work, sports, the arts, and almost every area of human endeavor can be dramatically influenced by how we think about our talents and abilities. People with a fixed mindset—those who believe that abilities are fixed—are less likely to flourish than those with a growth mindset—those who believe that abilities can be developed. Mindset reveals how great parents, teachers, managers, and athletes can put this idea to use to foster outstanding accomplishment.",
        "price": 520000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 50,
        "title": "Bên nhau trọn đời ",
        "author": "Cố Mạn ",
        "description": "Nhiều năm sau hiểu lầm, có rất nhiều cô gái để mắt đến Dĩ Thâm, nhưng lòng anh chẳng thể dung chứa ai ngoài cô gái đã mải miết theo đuổi anh suốt một năm ròng ở trường Đại học. Bảy năm sau gặp lại, cô trở thành nhiếp ảnh gia của một tạp chí, còn anh là luật sư nổi tiếng được nhiều người biết đến. Họ vô tình hội ngộ tại siêu thị, rồi một lần nữa bước vào đời nhau. Triệu Mặc Sênh của bảy năm sau không còn nhiều tự tin như cô gái theo đuổi Hà Dĩ Thâm năm nào. Thay vào đó, lần này là anh chủ động đến bên cô ấy, đòi cô phải kết hôn với mình. Cuộc hôn nhân đến với họ chớp nhoáng, mới đầu có phần khiên cưỡng, nhưng rồi thời gian đã chứng minh, trong lòng anh có cô, trong lòng cô có anh, thứ họ thiếu là khoảng không gian được gần nhau. Và một khi đã coi bản thân là người của đối phương, mọi hiểu lầm cũng theo đó được hóa giải, hạnh phúc lại tràn ngập như ánh nắng mùa xuân.",
        "price": 185000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 51,
        "title": "Tôi như ánh dương rạng rỡ ",
        "author": "Cố Mạn ",
        "description": "“Lời xin lỗi không nên có nhất trên thế giới này, chính là xin lỗi vì tình yêu của chính mình.” Tôi Như Ánh Dương Rạng Rỡ là tác phẩm mới nhất của Cố Mạn, tác giả của những tiểu thuyết ăn khách tại Việt Nam trong thời gian vừa qua: \"Bên Nhau Trọn Đời\", \"Yêu Em Từ Cái Nhìn Đầu Tiên\", \"Sam Sam Đến Đây Ăn Nào\". Một câu chuyện mang đậm phong cách lãng mạn nhẹ nhàng và khó quên của Cố Mạn, những cung bậc tinh tế trong tình yêu được tác giả đưa vào câu chuyện một cách khéo léo, người đọc có cảm giác như hòa cùng nhân vật chính trải nghiệm qua những thăng trầm trong tình cảm của cô.",
        "price": 145000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 52,
        "title": "Bố già ",
        "author": "Mario Puzo ",
        "description": "Thế giới ngầm được phản ánh trong tiểu thuyết Bố già là sự gặp gỡ giữa một bên là ý chí cương cường và nền tảng gia tộc chặt chẽ theo truyền thống mafia xứ Sicily với một bên là xã hội Mỹ nhập nhằng đen trắng, mảnh đất màu mỡ cho những cơ hội làm ăn bất chính hứa hẹn những món lợi kếch xù. Trong thế giới ấy, hình tượng Bố già được tác giả dày công khắc họa đã trở thành bức chân dung bất hủ trong lòng người đọc. Từ một kẻ nhập cư tay trắng đến ông trùm tột đỉnh quyền uy, Don Vito Corleone là con rắn hổ mang thâm trầm, nguy hiểm khiến kẻ thù phải kiềng nể, e dè, nhưng cũng được bạn bè, thân quyến xem như một đấng toàn năng đầy nghĩa khí. Nhân vật trung tâm ấy đồng thời cũng là hiện thân của một pho triết lí rất “đời” được nhào nặn từ vốn sống của hàng chục năm lăn lộn giữa chốn giang hồ bao phen vào sinh ra tử...",
        "price": 240000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 53,
        "title": "Số đỏ ",
        "author": "Vũ Trọng Phụng ",
        "description": "Bằng ngòi bút trào phúng độc đáo, Số đỏ lên án gay gắt cái xã hội tư sản thành thị Việt Nam đương thơi đang chạy theo lối sống \"văn minh\" rởm hết sức lố lăng đồi bại. Tác giả đã kích cay độc các phong trào \" Âu hoá\", \"thể thao\", \" giải phóng nữ quyền\" đang phát triển rầm rộ khi ấy, nhân danh \"văn minh\", \"tiến bộ\", \"cải cách xã hội\" mà thực chất chỉ là ăn chơi truỵ lạc, làm tiền, chà đạp trắng trợn lên mọi nề nếp đạo đức truyền thống.. Ngôn ngữ nghệ thuật của Vũ Trọng Phụng thấm đẫm cá tính sáng tạo. Một thứ ngôn ngữ vừa gai góc, sắc nhọn, mỉa mai, chát. Cũng là thứ ngôn ngữ hướng đến sự phô bày, lên án, tố cáo những mặt trái của xã hội nhưng dữ dội hơn so với các cây bút hiện thực khác.",
        "price": 45000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 54,
        "title": "Mindmap English Grammar ",
        "author": "Đỗ Nhung ",
        "description": "Ngữ Pháp Tiếng Anh Bằng Sơ Đồ Tư Duy có những đặc điểm sau đây: Giảng viên có thể hướng dẫn cho người học các chủ đề và chủ điểm ngữ pháp theo tư duy logic qua các sơ đồ tư duy tóm tắt dễ nhớ và dễ hiểu. Người học dễ dàng tự học và tham khảo trước khi làm các bài tập ngữ pháp hoặc sử dụng tiếng Anh. Hệ thống bài học được trình bày dạng \"mind map\" cách tân từ thấp lên cao nên người học yêu thích ngữ pháp tiếng Anh hơn. Sau khi học, hiểu, nắm vững các chủ đề, chủ điểm ngữ pháp, người học có thể tự vẽ lấy \"mind map\" của riêng mình.",
        "price": 45000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 55,
        "title": "Tâm Lý Học - Khái Lược Những Tư Tưởng Lớn ",
        "author": "DK ",
        "description": "Ta có thực sự là những cá nhân tự do với bản sắc riêng… hay tất cả chúng ta đều chỉ biết tuân phục số đông? Thiên tài là nhờ dưỡng dục hay tự nhiên? Vô thức điều khiển chúng ta như thế nào? Những câu hỏi như trên chính là tiền đề cho các công trình của nhiều tư tưởng gia và khoa học gia lớn của thế giới, trong một lĩnh vực giàu sức lôi cuốn, đó là tâm lí học. Với văn phong dễ hiểu và sáng sủa, Tâm lí học – Khái lược những tư tưởng lớn là tập hợp những bài viết ngắn gọn hàm súc giải thích rõ những điều khó hiểu, những sơ đồ giúp làm sáng tỏ những lí thuyết rối rắm, những trích dẫn dễ nhớ, cùng những minh họa dí dỏm giúp chúng ta chơi đùa với những kiến thức nền tảng về tâm lí học.",
        "price": 45000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 56,
        "title": "Mozart ",
        "author": "Maynard Solomon ",
        "description": "Mozart là một công trình nổi bật của nhà âm nhạc học Maynard Solomon, với giọng kể khách quan và dựa trên sự vượt trội về nguồn tư liệu, trong đó có nhiều tư liệu chưa từng xuất hiện trong bất kỳ tiểu sử nào trước đó về nhà soạn nhạc vĩ đại này. Cuốn sách đã giúp chúng ta được nhìn thấy người nhạc sĩ vĩ đại ở một góc nhìn khác biệt. Người đọc sẽ không còn thấy một Mozart thần thánh nữa, mà là một Mozart đời thường, một nhạc sĩ cũng phải kinh qua những bế tắc trong cuộc sống. Cuốn sách nói về các sự kiện, những bước ngoặt từ khi ông sinh ra vào năm 1756 và thời thơ ấu ở Salzburg cho đến thập niên đặc biệt của những buổi biểu diễn nổi tiếng ở các thủ đô châu Âu, nơi ông được các gia đình hoàng gia và khán giả yêu mến, tôn vinh như một thiên tài kỳ lạ. Cuốn sách cũng kể lại các bước thăng trầm của Mozart từ địa vị là người con được yêu thích của Salzburg trong những năm 1770, đến hành trình chinh phục Vienna cùng cuộc hôn nhân ở đó, từ những thăng trầm tài chính cho đến những nỗi sầu muộn ngày càng sâu sắc, cuối cùng kết thúc với sự ra đi ở tuổi còn rất trẻ của ông năm 1791…",
        "price": 450000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 59,
        "title": "Mindset: How You Can Fulfill Your Potential ",
        "author": "Carol S. Dweck ",
        "description": "World-renowned Stanford University psychologist Carol Dweck, in decades of research on achievement and success, has discovered a truly groundbreaking idea-the power of our mindset. Dweck explains why its not just our abilities and talent that bring us success-but whether we approach them with a fixed or growth mindset. She makes clear why praising intelligence and ability does not foster self-esteem and lead to accomplishment, but may actually jeopardize success. With the right mindset, we can motivate our kids and help them to raise their grades, as well as reach our own goals-personal and professional. Dweck reveals what all great parents, teachers, CEOs, and athletes already know: how a simple idea about the brain can create a \"love\" of learning and a resilience that is the basis of great accomplishment in every area.",
        "price": 535000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 60,
        "title": "Viet Nam Tourist Guidebook ",
        "author": "vietnamtourism ",
        "description": "Nhằm đẩy mạnh công tác xúc tiến, quảng bá du lịch Việt Nam, đồng thời phục vụ nhu cầu của đông đảo bạn đọc, Trung tâm Thông tin du lịch (Tổng cục Du lịch) vừa hoàn thành in tái bản lần thứ 7 cuốn sách hướng dẫn du lịch bằng tiếng Anh “Viet Nam Tourist Guidebook”. Đây là ấn phẩm có uy tín trên thị trường trong và ngoài nước hơn 10 năm nay, là cẩm nang hữu ích cho du khách và các hướng dẫn viên du lịch.",
        "price": 95000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 61,
        "title": "The Grammar Guidebook ",
        "author": "Susan Wise Bauer ",
        "description": "On its own or as a supplement to the Grammar for the Well-Trained Mind program, this complete compendium of grammar rules and examples will become an indispensable guide to writing—throughout high school, into college, and beyond...",
        "price": 49000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 62,
        "title": "Bến Xe ",
        "author": "Thương Thái Vi ",
        "description": "Thứ tôi có thể cho em trong cuộc đời này chỉ là danh dự trong sạch và một tương lai tươi đẹp mà thôi. Thế nhưng, nếu chúng ta có kiếp sau, nếu kiếp sau tôi có đôi mắt sáng, tôi sẽ ở bến xe này… đợi em. Mã hàng\t8935212349208 Tên Nhà Cung Cấp\tĐinh Tị Tác giả\tThương Thái Vi Người Dịch\tGreenrosetq NXB\tNXB Văn Học Năm XB\t2020 Ngôn Ngữ\tTiếng Việt Trọng lượng (gr)\t300 Kích Thước Bao Bì\t20.5 x 13 cm Số trang\t284 Hình thức\tBìa Mềm Sản phẩm hiển thị trong Đinh Tị Bến Xe (Tái Bản 2020) Bến Xe Thứ tôi có thể cho em trong cuộc đời này chỉ là danh dự trong sạch và một tương lai tươi đẹp mà thôi. Thế nhưng, nếu chúng ta có kiếp sau, nếu kiếp sau tôi có đôi mắt sáng, tôi sẽ ở bến xe này… đợi em.",
        "price": 210000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 63,
        "title": "Ielts The Ultimate Guide To Academic Reading ",
        "author": "Mike Witte ",
        "description": "Mike Wattie là một giaó viên xuất sắc. Trong lớp học của chúng tôi, tiếng Anh của tôi cải thiện đáng kể từ đó mà tôi đạt được điểm số cao trong phần thi Speaking kỳ thi IELTS. Hơn nữa, ông đã giúp tôi rất nhiều trong việc chỉnh sửa thư từ kinh doanh của mình.",
        "price": 105000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 64,
        "title": "The Presentation Book ",
        "author": "Emma Ledden ",
        "description": "The Presentation Book has been officially shortlisted in the \"New Manager\" category for the 2018 Management Book of the Year prize which has just been announced by the Chartered Management Institute (CMI) and the British Library. Make the next presentation you do, the best you’ve ever done. The Presentation Book shows how you can easily put your nerves behind you and calmly and confidently deliver a clear, sharp and very influential presentation.",
        "price": 322000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 65,
        "title": "Six thinking hats ",
        "author": "Edward De Bono ",
        "description": "Meetings are a crucial part of all our lives, but too often they go nowhere and waste valuable time. In Six Thinking Hats, Edward de Bono shows how meetings can be transformed to produce quick, decisive results every time. The Six Hats method is a devastatingly simple technique based on the brains different modes of thinking. The intelligence, experience and information of everyone is harnessed to reach the right conclusions quickly. These principles fundamentally change the way you work and interact. They have been adopted by businesses and governments around the world to end conflict and confusion in favour of harmony and productivity.",
        "price": 269000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 66,
        "title": "Tư Duy Đa Chiều ",
        "author": "Edward De Bono ",
        "description": "Theo đó, tác giả đưa ra sự đối sánh giữa tư duy đa chiều và tư duy chiều dọc thông thường trên các phương diện như tính chất, đặc trưng, cách vận hành của từng loại tư duy, mục đích,... và chỉ ra bản chất cơ bản và vai trò của tư duy đa chiều. Một số điểm nổi bật của tư duy đa chiều: Tư duy đa chiều liên quan đến việc phát triển những ý tưởng mới + Giải phóng khỏi các ý tưởng cũ và kích thích các ý tưởng mới là hai mặt song song của tư duy đa chiều.",
        "price": 120000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 67,
        "title": "Kỹ Năng Giao Tiếp Đỉnh Cao ",
        "author": "Lý Tử Quyên ",
        "description": "Từ xưa đến nay, con người giao tiếp không đơn thuần chỉ để truyền đạt những điều trong tâm tư mà nó còn là phương thức để người thấu hiểu người trong tình cảm, để thăng tiến trong sự nghiệp và để tỏ rõ sự hiểu biết của mình với thế giới bên ngoài. Biết im lặng đúng lúc cũng là một cách giao tiếp thông minh, biết nói đúng đủ để đem lại hiệu quả mà người nói muốn là điều ai cũng mong đạt được. Tất cả những kỹ năng được gói gọn trong “Giao tiếp đỉnh cao”- cuốn sách giúp bạn trở thành người làm chủ được khả năng giao tiếp, mở rộng mối quan hệ và đạt được thành công.",
        "price": 77000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 68,
        "title": "Nghệ Thuật Giao Tiếp Ứng Xử ",
        "author": "Gia Linh ",
        "description": "Nghệ thuật giao tiếp ứng xử Lời giới thiệu Nhân tố đầu tiên của sự thành công là biết gây dựng quan hệ tốt đẹp trong giao tiếp với mọi người. Một người muốn gặt hái thành công, thì quan hệ tốt đẹp với những người xung quanh là điều kiện tất yếu. Biết thể hiện những lời nói mượt mà và phù hợp sẽ giúp bạn “long lanh” hơn, thuận lợi hơn trong giao tiếp, nhất là trong xã hội ngày nay – một xã hội thương phẩm hóa cao độ. Chính vậy con người đã in lên dấu ấn của hàng hóa. Người tài có thể thoát ra khỏi hoàn cảnh cạnh tranh ngày một ác liệt để tìm kiếm được công việc như ý . Nhưng vấn đề là ở chỗ bạn có thể tự “quảng cáo” bản thân hay không ?. Một người tài chưa hẳn có tài giao tiếp nhưng, một người có tài giao tiếp ắt là một nhân tài. Đó cũng chính là điều mà cuốn: “Nghệ thuật giao tiếp” muốn gửi đến bạn đọc.",
        "price": 46000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 69,
        "title": "Thật Đơn Giản Thuyết Trình ",
        "author": "Richard Hall ",
        "description": "Đối với bất cứ ai, kể cả những nhà quản lý giàu kinh nghiệm, thuyết trình luôn là một thử thách khó khăn. Nhưng với Hall, thuyết trình không quá khó như bạn nghĩ nếu biết cách. Được đúc kết từ kinh nghiệm của những diễn giả hàng đầu thế giới, Thật đơn giản thuyết trình của Hall sẽ là một cẩm nang kỹ năng kinh doanh để giúp bạn hoàn thiện kỹ năng thuyết trình của bản thân.",
        "price": 79000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 70,
        "title": "Tư Duy Giản Đơn ",
        "author": "Đông Hải ",
        "description": "Cuốn sách thuộc thể loại kỹ năng, giúp người đọc hiểu đúng về tư duy, từ đó có những quan điểm đúng đắn để áp dụng vào công việc và cuộc sống một cách hiệu quả. Tác giả chỉ ra được nhiều thực trạng chưa tốt trong việc tự học, đồng thời cũng đưa ra được những phương pháp tốt/hữu ích hơn. Cuốn sách có bố cục 2 phần: “Tư duy và sự hình thành các quan niệm” và “Quan niệm về một số vấn đề của cuộc sống” (sự học, nghề nghiệp, đầu tư…). Cùng với cách trình bày vấn đề hấp dẫn, khoa học, mới lạ và các tình huống, ví dụ đa dạng khiến bản thảo vừa thú vị, mềm mại không khô cứng như những sách kỹ năng khác, nhưng vẫn chuyển tải được đầy đủ nội dung cần thiết về cách tư duy các vấn đề của cuộc sống cho bạn đọc.",
        "price": 200000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 71,
        "title": "Thoát Khỏi Bẫy Nhận Thức ",
        "author": "Thái Lũy Lỗi ",
        "description": "Đôi khi trong công việc và cuộc sống, chúng ta vô tình để bản thân rơi vào những chiếc bẫy nhận thức, khiến việc suy luận và đánh giá trở nên sai lệch, kém logic, ảnh hưởng đến phán đoán cũng như việc lựa chọn cách thức ứng xử cho phù hợp. Cuốn sách “Thoát khỏi bẫy nhận thức” sẽ giúp bạn một lần nữa kiểm nghiệm lại năng lực nhận thức của bản thân, học cách nhìn nhận vấn đề theo một cách sáng suốt, thực tế hơn.",
        "price": 110000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 72,
        "title": "Vua Thành Thái ",
        "author": "Nguyễn Hữu Nam ",
        "description": "Một cựu vương đã chấp nhận bị phế truất khỏi ngai vàng để rồi bước vào cuộc lưu đày biệt xứ ở đảo La Réunion (Phi châu), thay vì làm ông vua bù nhìn dưới ách cai trị của thực dân Pháp. Một cựu vương trong những ngày tháng lưu vong đã chọn lao động chân tay, tự nuôi sống gia đình thay vì nhận ân huệ từ chính quyền bản xứ. Một cựu vương cho đến chết vẫn “sống kiêu hãnh với hùng khí trường tồn”. Một cựu vương nổi danh với các giai thoại “tầm gái” trong dân gian, song những thiếu nữ thỏa hiệp với màn bắt cóc vào cung ấy chính là những nữ binh được gầy dựng để hỗ trợ nhà vua kháng Pháp…",
        "price": 116000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 73,
        "title": "Đột Phá Tư Duy ",
        "author": "Thái Lũy Lỗi ",
        "description": "Đây là một thời đại mâu thuẫn. Một mặt, internet mang lại vô số cơ hội, tạo nên nhiều người giàu mới, mỗi ngành nghề đều đang được thay đổi hoặc chờ được thay đổi; mặt khác, tầng lớp trung lưu vô cùng lo lắng, thiếu cảm giác an toàn. Chúng ta như thể có cơ hội vô hạn, nhưng lại không biết nắm bắt chúng như thế nào. Cái chúng ta thiếu không phải là thông tin, mà là nhận thức. Bởi vậy, chúng ta rất cần cuốn sách này của Thái Lũy Lỗi.",
        "price": 99000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 74,
        "title": "DK Life Stories Queen Elizabeth II ",
        "author": "DK ",
        "description": "At just 25 years of age, Princess Elizabeth succeeded King George VI to the British throne. This compelling book looks at Elizabeths life as both a public and private figure. It traces her early years as a princess, her experiences in the womens army during World War II, her coronation, and her life as queen both at home and in the public eye. The book looks at Elizabeth marriage to Prince Philip, her husband of more than 70 years, and her life as a mother to her four children, including her eldest son Prince Charles, the heir to the throne. In this biography book for kids ages 8-11, learn how Elizabeth has worked alongside 13 British prime ministers, met leaders from around the world, and has remained a stable presence as head of the British royal family.",
        "price": 125000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 75,
        "title": "The Communication Book: How to Say It, Mean It, and Make It Matter ",
        "author": "Emma Ledden ",
        "description": "Effective communication is too vital for you to leave to chance. Make sure what you are saying is simple, clear, compelling and gets results. This title is your straightforward, practical and expert guide to the secrets of great communication for all the important scenarios you face in business today. With Emma Ledden s expert help, quick tips and proven three-step visual approach, you will learn how to plan and prepare, know yourself, know your listener, keep in control, and much more.",
        "price": 325000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 76,
        "title": "Luật Im Lặng ",
        "author": "Mario Puzo ",
        "description": "“Tổ chức Mafia củng cố uy quyền bằng luật omerta nghĩa là làm thinh, câm nín. Dân quê Sicily kín miệng đến nỗi người lạ hỏi đường cũng làm thinh. Trong nội bộ Mafia có tội nào đáng chết bằng tội mật báo cảnh sát? Dù chỉ đi thưa lính, tố cáo một thằng vừa giết hụt mình hay vừa đánh đập mình có thương tích. Sau cùng luật omerta trở thành một đạo sống của mọi giới. Chồng con bị giết, con gái bị hãm hiếp, người đàn bà chính gốc Sicily chẳng bao giờ đi thưa lính, nhờ nhà nước giải quyết. Vì nhà nước không có quyền đó. Phải là Mafia!” Cái luật im lặng cổ xưa ấy chính là bức tường thành của Mafia suốt mấy trăm năm. Nhưng đó là ở nơi đất máu Sicily nhiều năm trước. Trên đất Mỹ, khi nhân loại sắp bước sang thiên niên kỉ mới, liệu omerta có còn cái quyền năng vô song để bảo vệ các ông trùm?",
        "price": 74000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 77,
        "title": "All The Rainbow's Colours ",
        "author": "Emma Ledden ",
        "description": "All The Rainbows Colours is an inspirational and warm-hearted book exploring diversity, inclusion, and belonging for children, parents, and teachers. With engaging lyrical text and colorful illustrations, this book is a must-have for every child’s bookshelf.",
        "price": 425000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 78,
        "title": "Ông Trùm Cuối Cùng ",
        "author": "Mario Puzo ",
        "description": "Mario Puzo đã làm nên tên tuổi với tiểu thuyết Bố Già – một tác phẩm về đề tài mafia. Và rồi, sau một phần tư thế kỉ, với Ông trùm cuối cùng, ông lại một lần nữa chiêu đãi độc giả một bữa tiệc thịnh soạn nào những âm mưu, thủ đoạn, bí ẩn đen tối pha trộn cùng một tình yêu không kém phần lãng mạn ngọt ngào. Lần này, câu chuyện kể về ông trùm già Domenico Clericuzio và những mưu tính của ông nhằm đưa tất cả các thành viên hòa nhập với xã hội hợp pháp. Tuy nhiên, kế hoạch tưởng chừng như thập toàn thập mỹ ấy lại không hoàn hảo như ông tưởng. Ông không tính được cái bí ẩn đẫm máu của quá khứ sẽ trở về ám ảnh hiện tại xán lạn, cũng như chẳng thể ngờ rằng trong đầu đứa cháu ông lại chất đầy những mưu đồ bẩn thỉu. Tất cả dường như đe dọa đến sự tồn vong của gia đình Mafia Clericuzio hùng mạnh nhất nước Mỹ.",
        "price": 117000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 79,
        "title": "Yêu em từ cái nhìn đầu tiên ",
        "author": "Cố Mạn ",
        "description": "Nhắc đến Yêu em từ cái nhìn đầu tiên có lẽ không cần dùng quá nhiều lời, bởi cùng với Sam Sam đến đây ăn nào, Bên nhau trọn đời, Yêu em từ cái nhìn đầu tiên đã làm nên tên tuổi của Cố Mạn tại Việt Nam.",
        "price": 117000,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    },
    {
        "id": 80,
        "title": "Sword Art Online - Tập 1 (Tái Bản)",
        "author": "Reki Kawahara",
        "description": "Sword Art Online 001 - Aincrad chưa phá đảo thì chưa thể thoát được ra ngoài!Game Over đồng nghĩa với cái chết thực sự của người chơi. Không hề hay biết chân tướng này, khoảng 10.000 người đã đăng nhập MMO thế hệ mới Sword Art Online (SAO), cùng mở màn cho một cuộc tử chiến tàn khốc. Kirito, nhân vật chính, là người đầu tiên trong số game thủ SAO biết chấp nhận chân tướng ấy. Và ở hiện trường của trò chơi - một thành nổi khổng lồ mang tên Aincrad, cậu ta dần dần hiển lộ được tài năng trong vai trò game thủ solo. Kirito vốn định duy trì tình trạng chiến đấu đơn độc đầy mạo hiểm đó cho đến khi đạt mục tiêu là vươn tới tầng cao nhất để phá đảo game, nhưng sau lời mời giàu sức thuyết phục của nữ kiếm sĩ Asuna, cậu quyết định sát cánh cùng cô. Cuộc gặp gỡ ấy đã tạo nên bước ngoặt có thể gọi là định mệnh đối với Kirito…",
        "price": 85700,
        "love": 0,
        "buy": 0,
        "left": 0,
        "discount": 0.0,
        "image": None
    }
]
    return book 

