# Generated by Django 5.0.8 on 2024-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_remove_user_fullname_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default='2023-07-07 07:07'),
            preserve_default=False,
        ),
    ]
