# Generated by Django 5.0.8 on 2024-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_remove_orderdetail_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
